import {useEffect,useState} from 'react'
import {api,json,ApiError,type User} from './api'

type Props={offline:boolean;busy:boolean;run:(f:()=>Promise<void>)=>void}

export function PublicAuth({setup,offline,busy,error,submit}:Props&{setup:boolean;error:string;submit:(u:string,p:string)=>void}){
 const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[localError,setError]=useState(''),[working,setWorking]=useState(false),[options,setOptions]=useState({registration:false,mail:false})
 useEffect(()=>{api<typeof options>('/auth/options').then(setOptions).catch(()=>{})},[])
 async function send(){setError('');setWorking(true);try{if(mode==='login')submit(email,password);else setMessage((await api<{message:string}>(mode==='register'?'/auth/register':'/auth/forgot-password',json('POST',{email,password}))).message)}catch(e){setError((e as Error).message)}finally{setWorking(false)}}
 return <div className="auth-page"><div className="auth-side"><div className="brand">LipoWatcher</div><div><h1>Chaque batterie.<br/>Chaque session.</h1><p>Votre carnet RC personnel.</p></div></div><div className="auth-form-wrap"><form className="auth-form" onSubmit={e=>{e.preventDefault();send()}}><h2>{setup?'Créer le compte initial':mode==='register'?'Créer un compte':mode==='forgot'?'Récupérer mon accès':'Se connecter'}</h2>{location.pathname==='/verify'&&<p className="notice">Connectez-vous au compte associé au courrier avant de confirmer. Pour une adresse ajoutée à un ancien compte, utilisez son ancien identifiant.</p>}<p>{setup?'Compte initial administrateur, réservé au premier démarrage.':mode==='register'?'Un e-mail vous permettra de vérifier votre adresse. Les comptes inscrits ne sont pas administrateurs.':mode==='forgot'?'La récupération utilise l’adresse renseignée sur votre compte. Pour un ancien compte sans adresse, contactez votre exploitant.':'Votre e-mail ou votre ancien identifiant. Un lien de vérification exige une connexion au compte associé avant confirmation.'}</p>{(error||localError)&&<p className="alert" role="alert">{error||localError}</p>}{message&&<p className="notice" role="status">{message}</p>}<label>{mode==='login'?'E-mail ou identifiant':'E-mail'}<input required type={mode==='login'?'text':'email'} value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label>{mode!=='forgot'&&<label>Mot de passe<input required minLength={12} maxLength={256} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='register'||setup?'new-password':'current-password'}/></label>}<button className="btn primary" disabled={offline||busy||working}>{mode==='forgot'?'Demander un lien':mode==='register'||setup?'Créer mon compte':'Se connecter'}</button>{!setup&&<div className="auth-links">{mode!=='login'&&<button type="button" onClick={()=>{setMode('login');setMessage('')}}>Connexion</button>}{options.registration&&mode!=='register'&&<button type="button" onClick={()=>{setMode('register');setMessage('')}}>Inscription</button>}{options.mail&&mode!=='forgot'&&<button type="button" onClick={()=>{setMode('forgot');setMessage('')}}>Mot de passe oublié</button>}{!options.mail&&<small>Inscription et récupération indisponibles : courrier non configuré.</small>}</div>}</form></div></div>
}

export function TokenPage({kind,token,offline,busy,run,done,reconnect}:{kind:string;token:string;done:()=>void;reconnect:()=>void}&Props){
 const [password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('')
 return <main className="container"><form className="panel user-form" onSubmit={e=>{e.preventDefault();run(async()=>{try{const r=await api<{message:string}>(kind==='verify'?'/auth/verify-email':'/auth/reset-password',json('POST',{token,password}));setMessage(r.message)}catch(err){if(err instanceof ApiError&&err.status===401)reconnect();else setError((err as Error).message)}})}}><h1>{kind==='verify'?'Vérifier mon adresse':'Nouveau mot de passe'}</h1><p>Cette action doit être confirmée. Le lien seul ne connecte pas votre compte.</p>{error&&<p className="alert">{error}</p>}{message?<><p className="notice">{message}</p><button type="button" className="btn primary" onClick={done}>Retour à l’application</button></>:<>{kind==='reset'&&<label>Nouveau mot de passe<input required minLength={12} maxLength={256} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label>}<button className="btn primary" disabled={offline||busy||!token}>{kind==='verify'?'Confirmer la vérification':'Remplacer le mot de passe'}</button>{!token&&<p className="alert">Lien absent. Demandez un nouveau message.</p>}</>}</form></main>
}

export function Account({user,offline,busy,run,updated}:{user:User;updated:(u:User)=>void}&Props){
 const [email,setEmail]=useState(user.email||''),[password,setPassword]=useState(''),[message,setMessage]=useState('')
 return <><h1>Mon compte</h1><section className="panel user-form"><p>Adresse : {user.email||'Non renseignée'} — {user.email_verified_at?'Vérifiée':'Non vérifiée'}</p><p>Les anciens comptes conservent leur identifiant et leurs données. Une adresse vérifiée est nécessaire pour transférer une batterie.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{setMessage((await api<{message:string}>('/auth/email',json('POST',{email,password}))).message);setPassword('')})}}><label>Adresse à ajouter ou remplacer<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe actuel<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="btn primary" disabled={offline||busy}>Envoyer la vérification</button></form>{message&&<p className="notice">{message}</p>}<div className="heading-actions"><button className="btn secondary" disabled={offline||busy} onClick={()=>run(async()=>{setMessage((await api<{message:string}>('/auth/resend-verification',{method:'POST'})).message)})}>Renvoyer le message</button><button className="btn secondary" disabled={offline||busy} onClick={()=>run(async()=>updated(await api<User>('/auth/me')))}>Actualiser la vérification</button></div><p>Le changement d’adresse ne prend effet qu’après vérification. Votre adresse n’est pas publiée dans les historiques techniques.</p></section></>
}
