import React, {useEffect, useState} from 'react'
import type {Battery, Entry, Charger} from './api'
import {loadDraft, saveDraft} from './drafts'

const statuses:Record<string,string>={active:'Active',storage:'Stockage',check:'À contrôler',retired:'Retirée'}
const kinds:Record<string,string>={charge:'Charge',test:'Décharge de test',storage:'Mise en stockage',flight:'Utilisation / vol',baseline:'Mesures de référence'}
const localDateTime=(value:Date)=>new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16)
const optionalNumber=(value:string|undefined)=>!value?.trim()?null:Number(value)
const values=(value:string)=>(!value.trim()?null:(value.includes(';')||value.includes(',')?value.split(/[;,]/):value.trim().split(/\s+/)).map(part=>part.trim()===''?null:Number(part.trim())))

export function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="iconbtn" onClick={close} aria-label="Fermer">×</button></div>{children}</div></div>}

const emptyBattery:Record<string,string>={number:'',brand:'',model:'',range:'',connector:'',weight_g:'',charge_max_a:'',charge_final_v:'',chemistry:'LiPo',cells:'4',nominal_mah:'',c_rating:'',charge_c:'',charge_rate_source:'',manufacturer_guide_url:'',manufacturer_guide_scope:'',acquired_on:'',condition:'new',prior_history:'unknown',prior_cycles:'',status:'active',notes:''}
export function BatteryModal({userId,initial,offline,busy,error='',close,save}:{userId:string;initial:Battery|null;offline:boolean;busy:boolean;error?:string;close:()=>void;save:(data:unknown)=>void}){
  const batteryId=initial?.id||'new-battery'
  const [form,setForm]=useState<Record<string,string>>(()=>loadDraft<Record<string,string>>(sessionStorage,userId,batteryId,'form')||(initial?Object.fromEntries(Object.keys(emptyBattery).map(k=>[k,String((initial as unknown as Record<string,unknown>)[k]??'')])):emptyBattery))
  useEffect(()=>saveDraft(sessionStorage,userId,batteryId,'form',form),[userId,batteryId,form])
  const field=(key:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setForm({...form,[key]:event.target.value})
  return <Modal close={close} title={initial?'Modifier la batterie':'Ajouter une batterie'}><form onSubmit={event=>{event.preventDefault();save({...form,cells:Number(form.cells),nominal_mah:Number(form.nominal_mah),c_rating:optionalNumber(form.c_rating),charge_c:optionalNumber(form.charge_c),weight_g:optionalNumber(form.weight_g),charge_max_a:optionalNumber(form.charge_max_a),charge_final_v:optionalNumber(form.charge_final_v),prior_cycles:optionalNumber(form.prior_cycles),acquired_on:form.acquired_on||null})}}>
    {error&&<p className="alert" role="alert">{error}</p>}
    <div className="form-grid"><label>{initial?'Numéro *':'Numéro(s) *'}<input required autoFocus value={form.number} onChange={field('number')} placeholder={initial?'001':'001, 002, 003'}/>{!initial&&<small>Séparez plusieurs numéros par une virgule pour créer un lot.</small>}</label><label>Chimie<select value={form.chemistry} onChange={field('chemistry')}><option>LiPo</option><option>LiHV</option><option>Li-ion</option><option>LiFe</option></select></label><label>Cellules *<input required type="number" min="1" max="16" value={form.cells} onChange={field('cells')}/></label><label>Capacité nominale (mAh) *<input required type="number" min="1" value={form.nominal_mah} onChange={field('nominal_mah')} placeholder="1300"/></label></div>
    {!initial&&<p className="guide-intro">Pour une batterie neuve, un guide facultatif de première utilisation sera proposé après l’ajout.</p>}
    <details className="advanced"><summary>Informations complémentaires</summary><div className="form-grid"><label>Marque<input value={form.brand} onChange={field('brand')}/></label><label>Modèle<input value={form.model} onChange={field('model')}/></label><label>Gamme<input value={form.range||''} onChange={field('range')}/></label><label>Connecteur<input value={form.connector||''} onChange={field('connector')}/></label><label>Poids (g)<input type="number" step="any" value={form.weight_g||''} onChange={field('weight_g')}/></label><label>Maximum de charge documenté (A)<input type="number" step="any" value={form.charge_max_a||''} onChange={field('charge_max_a')}/></label><label>Tension finale documentée du pack (V)<input type="number" step="any" value={form.charge_final_v||''} onChange={field('charge_final_v')}/></label><label>C de décharge annoncé<input type="number" step="0.1" min="0.1" value={form.c_rating} onChange={field('c_rating')}/></label><label>Taux de charge maximal documenté pour le pack (C)<input type="number" step="0.1" min="0.1" value={form.charge_c} onChange={field('charge_c')}/></label><label>Source du maximum de charge<input value={form.charge_rate_source} onChange={field('charge_rate_source')} placeholder="Notice de la référence…"/></label><label>Date d’achat / réception<input type="date" value={form.acquired_on} onChange={field('acquired_on')}/></label><label>État<select value={form.condition} onChange={field('condition')}><option value="new">Neuve</option><option value="used">Occasion</option></select></label><label>Historique antérieur<select value={form.prior_history} onChange={field('prior_history')}><option value="unknown">Inconnu</option><option value="known">Connu</option></select></label><label>Cycles antérieurs déclarés<input type="number" min="0" value={form.prior_cycles} onChange={field('prior_cycles')}/></label><label>Statut<select value={form.status} onChange={field('status')}>{Object.entries(statuses).map(([key,value])=><option value={key} key={key}>{value}</option>)}</select></label><label>URL de la procédure fabricant<input type="url" value={form.manufacturer_guide_url} onChange={field('manufacturer_guide_url')}/></label><label>Référence et champ d’application de la procédure<input value={form.manufacturer_guide_scope} onChange={field('manufacturer_guide_scope')} placeholder="Référence exacte, révision…"/></label></div><label>Notes<textarea rows={3} value={form.notes} onChange={field('notes')}/></label></details>
    <div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Annuler</button><button type="submit" className="btn primary" disabled={busy||offline}>{initial?'Enregistrer':'Ajouter la batterie'}</button></div>
  </form></Modal>
}

const entryKeys=['kind','occurred_at','added_mah','discharged_mah','cutoff_v','charger','charger_id','charger_channel','initial_percent','initial_percent_source','final_percent','before_v','after_v','resistance_mohm','current_a','ambient_c','aircraft','duration_min','voltage_sag','heat','notes']
export function EntryModal({userId,batteryId,defaultKind,initial,cells,chargers,lastChoice,offline,busy,error='',close,save}:{userId:string;batteryId:string;defaultKind:string;initial:Entry|null;cells:number;chargers:Charger[];lastChoice:Entry|null;offline:boolean;busy:boolean;error?:string;close:()=>void;save:(data:unknown)=>void}){
  const entryId=initial?.id||'new-'+defaultKind
  const [form,setForm]=useState<Record<string,string>>(()=>loadDraft<Record<string,string>>(sessionStorage,userId,batteryId,entryId)||(initial?Object.fromEntries(entryKeys.map(key=>{const value=(initial as unknown as Record<string,unknown>)[key];return [key,Array.isArray(value)?value.map(part=>part??'').join(' ; '):key==='occurred_at'?localDateTime(new Date(String(value))):String(value??'')]})):{kind:defaultKind,occurred_at:localDateTime(new Date()),added_mah:'',discharged_mah:'',cutoff_v:'',charger:lastChoice?.charger||'',charger_id:lastChoice?.charger_id||'',charger_channel:String(lastChoice?.charger_channel||''),initial_percent:'',initial_percent_source:'',final_percent:'',before_v:'',after_v:'',resistance_mohm:'',current_a:'',ambient_c:'',aircraft:'',duration_min:'',voltage_sag:'',heat:'',notes:''}))
  useEffect(()=>saveDraft(sessionStorage,userId,batteryId,entryId,form),[userId,batteryId,entryId,form])
  const field=(key:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setForm({...form,[key]:event.target.value})
  const input=(key:string,title:string,extra:React.InputHTMLAttributes<HTMLInputElement>={})=><label>{title}<input value={form[key]} onChange={field(key)} {...extra}/></label>
  return <Modal close={close} title={initial?'Corriger une session':'Ajouter une session'}><form onSubmit={event=>{event.preventDefault();const data:Record<string,unknown>={...form,occurred_at:new Date(form.occurred_at).toISOString()};for(const key of ['added_mah','discharged_mah','cutoff_v','initial_percent','final_percent','current_a','ambient_c','duration_min'])data[key]=optionalNumber(form[key]);data.charger_id=form.charger_id||null;data.charger_channel=optionalNumber(form.charger_channel||'');for(const key of ['before_v','after_v','resistance_mohm'])data[key]=values(form[key]);save(data)}}>
    {error&&<p className="alert" role="alert">{error}</p>}
    {form.kind==='baseline'&&<p className="guide-intro">Notez le moment du relevé, l’état de charge et son origine, le chargeur, la température et les conditions. Les mesures par cellule restent facultatives.</p>}
    <div className="form-grid"><label>Type de session<select value={form.kind} onChange={field('kind')}>{Object.entries(kinds).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>{input('occurred_at',form.kind==='baseline'?'Date et heure du relevé':'Date et heure',{type:'datetime-local',required:true})}{form.kind==='charge'&&input('added_mah','mAh ajoutés *',{type:'number',min:0,required:true,inputMode:'numeric'})}{form.kind==='test'&&input('discharged_mah','mAh déchargés *',{type:'number',min:0,required:true,inputMode:'numeric'})}</div>
    <details className="advanced" open={form.kind==='baseline'?true:undefined}><summary>Mesures et détails facultatifs</summary><div className="form-grid"><label>Appareil enregistré, facultatif<select value={form.charger_id||''} onChange={e=>setForm({...form,charger_id:e.target.value,charger_channel:'',charger:e.target.value?chargers.find(c=>c.id===e.target.value)?.name||'':form.charger})}><option value="">Texte libre / aucun appareil</option>{chargers.filter(c=>c.status==='active'||c.id===initial?.charger_id).map(c=><option key={c.id} value={c.id}>{c.name}{c.status==='archived'?' (archivé)':''} · {c.brand} {c.model}</option>)}</select></label>{form.charger_id?<label>Canal, facultatif<select value={form.charger_channel||''} onChange={field('charger_channel')}><option value="">Non renseigné</option>{Array.from({length:Math.max(chargers.find(c=>c.id===form.charger_id)?.channels||1,Number(initial?.charger_channel)||0)},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}</option>)}</select></label>:input('charger','Nom du chargeur (texte libre)')}{input('initial_percent',form.kind==='baseline'?'État de charge au relevé (%)':'Pourcentage initial estimé',{type:'number',min:0,max:100,step:'0.1'})}{input('initial_percent_source',form.kind==='baseline'?"Origine de l’état de charge":'Origine de cette estimation',{placeholder:'Tension, télémétrie…'})}{input('final_percent','Pourcentage final',{type:'number',min:0,max:100,step:'0.1'})}{input('before_v',`Tensions avant (${cells} cellules, V)`,{placeholder:'3.75 ; ; 3.76 (case vide = non mesurée)'})}{input('after_v',`Tensions après (${cells} cellules, V)`,{placeholder:'4.20 ; 4.19 ; …'})}{input('resistance_mohm',`Résistances (${cells} cellules, mΩ)`,{placeholder:'5 ; ; 6 (case vide = non mesurée)'})}{input('current_a','Courant (A)',{type:'number',min:0,step:'0.01'})}{input('ambient_c','Température ambiante (°C)',{type:'number',step:'0.1'})}{form.kind==='test'&&input('cutoff_v','Tension de coupure (V)',{type:'number',min:0,step:'0.01'})}{form.kind==='flight'&&<>{input('aircraft','Appareil utilisé')}{input('duration_min','Durée (minutes)',{type:'number',min:0,step:'0.1'})}{input('voltage_sag','Chute de tension observée')}{input('heat','Chauffe observée')}</>}</div><label>Conditions et notes<textarea rows={3} value={form.notes} onChange={field('notes')}/></label></details>
    <div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Annuler</button><button type="submit" className="btn primary" disabled={busy||offline}>Enregistrer</button></div>
  </form></Modal>
}
