import {useEffect, useState} from 'react'
import {api, json, type Battery, type Charger, type Lot, type Model, type User} from './api'
import {Modal} from './Forms'

type Props={view:string;user:User;offline:boolean;busy:boolean;run:(work:()=>Promise<void>)=>void;go:(path:string)=>void}
type Field={key:string;label:string;type?:string;required?:boolean;options?:[string,string][]}
const chemistry:[string,string][]=['LiPo','LiHV','Li-ion','LiFe'].map(x=>[x,x])
const modelFields:Field[]=[{key:'brand',label:'Marque'},{key:'range',label:'Gamme'},{key:'model',label:'Référence',required:true},{key:'chemistry',label:'Chimie',options:chemistry},{key:'cells',label:'Cellules',type:'number',required:true},{key:'nominal_mah',label:'Capacité nominale (mAh)',type:'number',required:true},{key:'c_rating',label:'C de décharge annoncé',type:'number'},{key:'connector',label:'Connecteur'},{key:'weight_g',label:'Poids (g)',type:'number'},{key:'charge_c',label:'Maximum de charge documenté (C)',type:'number'},{key:'charge_max_a',label:'Maximum de charge documenté (A)',type:'number'},{key:'charge_final_v',label:'Tension finale documentée du pack (V)',type:'number'},{key:'charge_rate_source',label:'Source des limites de charge'},{key:'manufacturer_guide_url',label:'Lien fabricant',type:'url'},{key:'manufacturer_guide_scope',label:'Référence / champ d’application'},{key:'provenance',label:'Provenance des caractéristiques'},{key:'notes',label:'Notes',type:'textarea'}]
const lotFields:Field[]=[{key:'name',label:'Nom du lot',required:true},{key:'acquired_on',label:'Date d’achat / réception',type:'date'},{key:'seller',label:'Vendeur'},{key:'total_price',label:'Prix total',type:'number'},{key:'currency',label:'Devise (3 lettres)',required:true},{key:'condition',label:'État à l’achat',options:[['new','Neuves'],['used','Occasion']]},{key:'notes',label:'Notes',type:'textarea'}]
const chargerFields:Field[]=[{key:'name',label:'Nom personnel de cet appareil',required:true},{key:'brand',label:'Marque'},{key:'model',label:'Modèle'},{key:'channels',label:'Nombre de canaux',type:'number',required:true},{key:'firmware',label:'Version du firmware'},{key:'status',label:'Statut',options:[['active','Actif'],['archived','Archivé']]},{key:'notes',label:'Notes',type:'textarea'}]
const defaults:Record<string,string>={chemistry:'LiPo',cells:'3',nominal_mah:'',currency:'EUR',condition:'new',channels:'1',status:'active'}
const stateText:Record<string,string>={private:'Privé',proposed:'Proposé',published:'Publié',archived:'Archivé',active:'Actif'}
const payload=(form:Record<string,string>,fields:Field[])=>Object.fromEntries(fields.map(f=>[f.key,f.type==='number'?(form[f.key]?.trim()?Number(form[f.key]):null):f.key==='acquired_on'?(form[f.key]||null):(form[f.key]||'')]))

function Fields({fields,form,setForm}:{fields:Field[];form:Record<string,string>;setForm:(f:Record<string,string>)=>void}){return <div className="form-grid">{fields.map(f=><label key={f.key}>{f.label}{f.required?' *':''}{f.options?<select value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}>{f.options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:f.type==='textarea'?<textarea rows={3} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input required={f.required} type={f.type||'text'} step={f.type==='number'?'any':undefined} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div>}

export function Inventory({view,user,offline,busy,run,go}:Props){
  const [models,setModels]=useState<Model[]>([]),[lots,setLots]=useState<Lot[]>([]),[chargers,setChargers]=useState<Charger[]>([]),[batteries,setBatteries]=useState<Battery[]>([]),[review,setReview]=useState<Model[]>([])
  const [q,setQ]=useState(''),[filter,setFilter]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false)
  const [editing,setEditing]=useState<Model|Lot|Charger|null|false>(false),[form,setForm]=useState<Record<string,string>>({}),[selectedLot,setSelectedLot]=useState<Lot|null>(null),[members,setMembers]=useState<string[]>([]),[history,setHistory]=useState<Record<string,unknown>[]|null>(null)
  const [creating,setCreating]=useState(false),[modelId,setModelId]=useState(''),[quantity,setQuantity]=useState('1'),[start,setStart]=useState('001'),[numbers,setNumbers]=useState(''),[preview,setPreview]=useState<{numbers:string[];specs:Model;model_revision:number}|null>(null),[withLot,setWithLot]=useState(view==='lots'),[lotForm,setLotForm]=useState<Record<string,string>>({currency:'EUR',condition:'new',name:''})
  const isModels=view==='models'||view==='catalogue'
  const fields=view==='models'?modelFields:view==='lots'?lotFields:chargerFields
  async function load(){
    if(isModels){setModels(await api<Model[]>(`/${view==='models'?'models':'catalogue'}?q=${encodeURIComponent(q)}&${view==='models'?'status':'chemistry'}=${encodeURIComponent(filter)}`));if(view==='catalogue'&&user.is_admin)setReview(await api<Model[]>('/catalogue/review'))}
    else if(view==='lots'){const [l,b,m]=await Promise.all([api<Lot[]>(`/lots?q=${encodeURIComponent(q)}&condition=${filter}`),api<Battery[]>('/batteries'),api<Model[]>('/models')]);setLots(l);setBatteries(b);setModels(m.filter(x=>x.status!=='archived'))}
    else setChargers(await api<Charger[]>(`/chargers?q=${encodeURIComponent(q)}&status=${filter}`))
    setReady(true)
  }
  function act(work:()=>Promise<void>){setError('');run(async()=>{try{await work()}catch(e){setError((e as Error).message);throw e}})}
  useEffect(()=>{act(load)},[view,q,filter])
  useEffect(()=>{const id=new URLSearchParams(location.search).get('open');if(view==='lots'&&id)act(()=>openLot(id))},[view])
  function edit(item:Model|Lot|Charger|null){setError('');setEditing(item);setForm(Object.fromEntries(fields.map(f=>[f.key,String(item?(item as unknown as Record<string,unknown>)[f.key]??'':defaults[f.key]??'')])))}
  function begin(model?:Model){setError('');setModelId(model?.id||models.find(m=>m.status!=='archived')?.id||'');setQuantity('1');setStart('001');setNumbers('');setPreview(null);setWithLot(view==='lots');setCreating(true)}
  async function openLot(id:string){const l=await api<Lot>('/lots/'+id);const b=await api<Battery[]>('/batteries');setBatteries(b);setSelectedLot(l);setMembers(l.batteries?.map(x=>x.id)||[])}
  const disabled=offline||busy
  const title=view==='models'?'Modèles':view==='lots'?'Lots':view==='chargers'?'Mes chargeurs':'Catalogue'
  const cardModel=(m:Model,moderating=false)=><article className="panel inventory-card" key={m.id}>
    <div className="section-heading"><h2>{[m.brand,m.range,m.model].filter(Boolean).join(' ')}</h2><span className="badge">{moderating?'Proposition':stateText[m.status]} · rév. {moderating?m.revision:m.status==='published'?m.published_revision:m.revision}</span></div>
    <p>{m.chemistry} · {m.cells}S · {m.nominal_mah} mAh {m.connector&&'· '+m.connector}</p>
    <small>Caractéristiques déclarées ou documentées. La validation administrative ne constitue pas une certification technique.</small>
    {view==='models'&&m.status==='published'&&m.revision!==m.published_revision&&<p className="notice">Fiche de travail · révision {m.revision}. Le catalogue et la création de batteries utilisent la révision publiée {m.published_revision}, affichée dans l’aperçu.</p>}
    {m.pending&&<p className="notice">{m.status==='published'?'Modification en attente ; la version publiée reste disponible.':'Proposition en attente de validation.'}</p>}
    {m.rejection_reason&&<p className="notice">Motif de refus : {m.rejection_reason}</p>}
    {m.charge_c!=null&&<p>Maximum déclaré : {m.charge_c}C · source : {m.charge_rate_source}</p>}
    {m.charge_max_a!=null&&<p>Maximum déclaré : {m.charge_max_a} A · source : {m.charge_rate_source}</p>}
    {m.charge_final_v!=null&&<p>Tension finale du pack déclarée : {m.charge_final_v} V</p>}
    {m.c_rating!=null&&<p>C de décharge annoncé : {m.c_rating}</p>}{m.weight_g!=null&&<p>Poids : {m.weight_g} g</p>}
    {m.manufacturer_guide_url&&<p><a href={m.manufacturer_guide_url} target="_blank" rel="noopener noreferrer">Source fabricant ↗</a> · {m.manufacturer_guide_scope}</p>}
    {m.provenance&&<p>Provenance : {m.provenance}</p>}{m.notes&&<p>{m.notes}</p>}<small>Auteur : {m.author_id} · créé le {new Date(m.created_at).toLocaleDateString('fr-FR')} · modifié le {new Date(m.updated_at).toLocaleDateString('fr-FR')}{m.origin_model_id&&` · copie de la révision ${m.origin_revision}`}</small>
    <div className="inventory-actions">{moderating?<><button className="btn primary" disabled={disabled} onClick={()=>act(async()=>{await api(`/catalogue/${m.id}/decision`,json('POST',{action:'publish',expected_revision:m.revision}));await load()})}>Publier cette révision</button><button className="btn secondary" disabled={disabled} onClick={()=>{const reason=prompt('Motif du refus');if(reason)act(async()=>{await api(`/catalogue/${m.id}/decision`,json('POST',{action:'reject',expected_revision:m.revision,reason}));await load()})}}>Refuser avec motif</button></>:view==='catalogue'?<><button className="btn primary" disabled={disabled} onClick={()=>act(async()=>{await api(`/catalogue/${m.id}/copy`,json('POST',{}));go('/models')})}>Copier dans mes modèles</button><button className="btn secondary" disabled={disabled} onClick={()=>begin(m)}>Créer des batteries</button>{user.is_admin===1&&<button className="btn ghost" disabled={disabled} onClick={()=>{if(confirm('Archiver ce modèle du catalogue ? Les batteries restent conservées.'))act(async()=>{await api(`/catalogue/${m.id}/decision`,json('POST',{action:'archive',expected_revision:m.decision_revision??m.revision}));await load()})}}>Archiver</button>}</>:<>{m.status!=='archived'&&<><button className="btn primary" disabled={disabled} onClick={()=>begin(m)}>Créer des batteries</button><button className="btn secondary" disabled={disabled} onClick={()=>edit(m)}>Modifier</button></>}{m.status==='private'&&<><button className="btn ghost" disabled={disabled} onClick={()=>act(async()=>{await api(`/models/${m.id}/submit`,json('POST',{}));await load()})}>Proposer au catalogue</button><button className="btn ghost" disabled={disabled} onClick={()=>act(async()=>{await api(`/models/${m.id}/archive`,json('POST',{}));await load()})}>Archiver</button></>}</>}
    <button className="btn ghost" disabled={disabled} onClick={()=>act(async()=>{if(view==='models'&&!moderating){const r=await api<{history:Record<string,unknown>[]}>('/models/'+m.id);setHistory(r.history)}else setHistory(await api<Record<string,unknown>[]>(`/catalogue/${m.id}/history`))})}>Révisions</button></div>
  </article>
  return <><div className="page-heading"><div><div className="eyebrow">MON ATELIER</div><h1>{title}</h1><p>{view==='catalogue'?'Modèles publiés après validation administrative. Aucun historique ou achat privé partagé.':view==='models'?'Des caractéristiques réutilisables ; chaque batterie conserve son propre instantané.':view==='lots'?'Regroupez vos achats sans fusionner les historiques.':'Identifiez chaque appareil physique. La sélection ne crée aucune connexion USB.'}</p></div>{view!=='catalogue'&&<div className="heading-actions"><button className="btn primary" disabled={disabled} onClick={()=>edit(null)}>Ajouter {view==='models'?'un modèle':view==='lots'?'un lot':'un chargeur'}</button>{view==='lots'&&<button className="btn secondary" disabled={disabled||!models.length} onClick={()=>begin()}>Création rapide</button>}</div>}</div>
    <div className="toolbar"><label className="search"><input aria-label="Recherche" placeholder="Rechercher…" value={q} onChange={e=>setQ(e.target.value)}/></label><select aria-label="Filtrer" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tous</option>{(view==='models'?['private','proposed','published','archived']:view==='catalogue'?chemistry.map(([v])=>v):view==='lots'?['new','used']:['active','archived']).map(s=><option key={s} value={s}>{stateText[s]||({new:'Neuves',used:'Occasion'} as Record<string,string>)[s]||s}</option>)}</select></div>
    {error&&<p className="alert" role="alert">{error}</p>}
    {!ready?<p>Chargement…</p>:<div className="inventory-list">{isModels?models.map(m=>cardModel(m)):view==='lots'?lots.map(l=><article className="panel inventory-card" key={l.id}><h2>{l.name}</h2><p>{l.acquired_on||'Date non renseignée'} · {l.condition==='new'?'Neuves':'Occasion'} · {l.battery_count} batterie(s)</p>{l.seller&&<p>Vendeur : {l.seller}</p>}{l.total_price!=null&&<p>{l.total_price} {l.currency}</p>}<p>{l.notes}</p><div className="inventory-actions"><button className="btn primary" onClick={()=>act(()=>openLot(l.id))}>Voir / associer les batteries</button><button className="btn secondary" disabled={disabled} onClick={()=>edit(l)}>Modifier</button><button className="btn ghost" disabled={disabled} onClick={()=>{if(confirm('Supprimer ce regroupement ? Les batteries et sessions seront conservées.'))act(async()=>{await api('/lots/'+l.id,{method:'DELETE'});await load()})}}>Supprimer le regroupement</button></div></article>):chargers.map(c=><article className="panel inventory-card" key={c.id}><h2>{c.name}</h2><p>{c.brand} {c.model} · {c.channels} canal(aux) · {stateText[c.status]}</p>{c.firmware&&<p>Firmware : {c.firmware}</p>}<small>Appareil : {c.id}</small><p>{c.notes}</p><div className="inventory-actions"><button className="btn secondary" disabled={disabled} onClick={()=>edit(c)}>Modifier</button><button className="btn ghost" disabled={disabled} onClick={()=>act(async()=>{await api('/chargers/'+c.id,json('PUT',{...c,status:c.status==='active'?'archived':'active'}));await load()})}>{c.status==='active'?'Archiver':'Réactiver'}</button></div></article>)}{!(isModels?models.length:view==='lots'?lots.length:chargers.length)&&<div className="empty"><h3>{q||filter?'Aucun résultat':'Aucune fiche pour le moment'}</h3><p>{view==='catalogue'?'Les modèles apparaissent ici après validation ; aucune donnée n’est ajoutée automatiquement.':'Ajoutez votre première fiche avec le bouton ci-dessus.'}</p></div>}</div>}
    {view==='catalogue'&&user.is_admin===1&&<section className="panel"><h2>Propositions à examiner</h2><p>Vérifiez caractéristiques, sources et champ d’application avant publication.</p>{review.length?review.map(m=>cardModel(m,true)):<p>Aucune proposition en attente.</p>}</section>}
    {editing!==false&&<Modal title={(editing?'Modifier':'Ajouter')+' '+(view==='models'?'un modèle':view==='lots'?'un lot':'un chargeur')} close={()=>setEditing(false)}><form onSubmit={e=>{e.preventDefault();act(async()=>{await api(`/${view}${editing?'/'+editing.id:''}`,json(editing?'PUT':'POST',payload(form,fields)));setEditing(false);await load()})}}>{view==='models'&&<p className="notice">Les limites sont déclarées ou documentées, distinctes du courant choisi pour une session. Une modification de modèle ne change aucune batterie existante.</p>}{error&&<p className="alert">{error}</p>}<Fields fields={fields} form={form} setForm={setForm}/><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setEditing(false)}>Annuler</button><button className="btn primary" disabled={disabled}>Enregistrer</button></div></form></Modal>}
    {creating&&<Modal title="Créer des batteries depuis un modèle" close={()=>setCreating(false)}><form onSubmit={e=>{e.preventDefault();act(async()=>{const r=await api<{lot:Lot|null;batteries:Battery[]}>('/lots/from-model',json('POST',{model_id:modelId,expected_revision:preview?.model_revision,numbers:numbers.split(/[;,\n]/).map(s=>s.trim()).filter(Boolean),lot:withLot?payload(lotForm,lotFields):null,condition:lotForm.condition}));setCreating(false);if(r.lot){await load();await openLot(r.lot.id)}else go('/b/'+r.batteries[0].id)})}}>{error&&<p className="alert">{error}</p>}<div className="form-grid"><label>Modèle<select required value={modelId} onChange={e=>{setModelId(e.target.value);setPreview(null)}}><option value="">Choisir…</option>{models.filter(m=>m.status!=='archived').map(m=><option key={m.id} value={m.id}>{m.brand} {m.model} · {m.chemistry} {m.cells}S</option>)}</select></label><label>Quantité<input required type="number" min="1" max="100" value={quantity} onChange={e=>{setQuantity(e.target.value);setPreview(null)}}/></label><label>Premier numéro proposé<input required pattern="[0-9]+" value={start} onChange={e=>{setStart(e.target.value);setPreview(null)}}/></label></div><button type="button" className="btn secondary" disabled={disabled||!modelId} onClick={()=>act(async()=>{const p=await api<{numbers:string[];specs:Model;model_revision:number}>('/lots/preview',json('POST',{model_id:modelId,quantity:Number(quantity),start_number:start}));setPreview(p);setNumbers(p.numbers.join(', '))})}>Préparer l’aperçu</button>
      {preview&&<section className="notice"><strong>Aperçu · modèle révision {preview.model_revision}</strong><p>{preview.specs.brand} {preview.specs.model} · {preview.specs.chemistry} {preview.specs.cells}S · {preview.specs.nominal_mah} mAh</p><label>Numéros proposés, modifiables<textarea required value={numbers} onChange={e=>setNumbers(e.target.value)}/></label><p>Les numéros occupés ont été évités. Une collision à l’enregistrement annule toute la création.</p></section>}
      <label className="guide-step"><input type="checkbox" checked={withLot} onChange={e=>setWithLot(e.target.checked)}/><span>Regrouper dans un lot d’achat privé</span></label>{withLot?<Fields fields={lotFields} form={lotForm} setForm={setLotForm}/>:<Fields fields={lotFields.filter(f=>f.key==='condition')} form={lotForm} setForm={setLotForm}/>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setCreating(false)}>Annuler</button><button className="btn primary" disabled={disabled||!preview||!numbers.trim()}>Créer l’ensemble</button></div></form></Modal>}
    {selectedLot&&<Modal title={selectedLot.name} close={()=>setSelectedLot(null)}>{error&&<p className="alert">{error}</p>}<p>Associer ou retirer une batterie conserve toutes ses sessions. Une batterie appartient à un seul lot ; la sélectionner ici la déplace depuis son lot précédent.</p><div className="lot-members">{batteries.length?batteries.map(b=><div className="member-row" key={b.id}><label><input type="checkbox" checked={members.includes(b.id)} disabled={disabled} onChange={e=>setMembers(e.target.checked?[...members,b.id]:members.filter(id=>id!==b.id))}/><span>#{b.number} · {b.brand} {b.model}{b.lot_id&&b.lot_id!==selectedLot.id?' · dans un autre lot':''}</span></label><button className="btn ghost" onClick={()=>go('/b/'+b.id)}>Fiche</button></div>):<p>Aucune batterie à associer.</p>}</div><div className="modal-actions"><button className="btn secondary" onClick={()=>setSelectedLot(null)}>Fermer</button><button className="btn primary" disabled={disabled} onClick={()=>act(async()=>{await api('/lots/'+selectedLot.id+'/members',json('PUT',{battery_ids:members}));setSelectedLot(null);await load()})}>Enregistrer les associations</button></div></Modal>}
    {history&&<Modal title="Historique des révisions" close={()=>setHistory(null)}><p>La publication est une validation administrative des données déclarées.</p>{history.map((h,i)=><article className="revision" key={i}><strong>Révision {String(h.revision)} · {String(h.event)}</strong><small>{String(h.created_at)} · auteur de l’action : {String(h.actor_id)}</small>{Boolean(h.reason)&&<p>{String(h.reason)}</p>}<pre>{JSON.stringify(h.data,null,2)}</pre></article>)}</Modal>}
  </>
}
