import React, {useEffect, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BatteryCharging, BatteryFull, ChartNoAxesCombined, ChevronLeft, CirclePlus, Download, LogOut, Menu, Printer, QrCode, Search, Settings, X} from 'lucide-react'
import jsQR from 'jsqr'
import {api, json, ApiError, type Battery, type Entry, type User, type Charger} from './api'
import {CellTrends} from './CellTrends'
import {filterMeasurements,lastDeviceChoice} from './sessionDevices'
import {Inventory} from './Inventory'
import {PublicAuth,Account,TokenPage} from './Accounts'
import {Transfers,TransferProposal} from './Transfers'
import {FirstUseGuide} from './FirstUseGuide'
import {clearDraft} from './drafts'
import {parseQrIdentifier} from './qr'
import {BatteryModal, EntryModal, Modal} from './Forms'
import './style.css'
const statusText:Record<string,string>={active:'Active',storage:'Stockage',check:'À contrôler',retired:'Retirée'}
const kindText:Record<string,string>={charge:'Charge',test:'Décharge de test',storage:'Mise en stockage',flight:'Utilisation / vol',baseline:'Mesures de référence'}
function formatted(n:number|undefined|null){return n==null?'—':new Intl.NumberFormat('fr-FR').format(n)}
function Button({children,onClick,variant='primary',type='button',disabled=false}:{children:React.ReactNode;onClick?:()=>void;variant?:string;type?:'button'|'submit';disabled?:boolean}){return <button type={type} className={'btn '+variant} onClick={onClick} disabled={disabled}>{children}</button>}
function App(){
  const [linkToken]=useState(()=>{const value=new URLSearchParams(location.hash.slice(1)).get('token')||'';if(location.hash)history.replaceState({},'',location.pathname+location.search);return value})
  const [transferOpen,setTransferOpen]=useState(false),[annotation,setAnnotation]=useState<Entry|null>(null),[annotationText,setAnnotationText]=useState('')
  const [user,setUser]=useState<User|null>(null),[setup,setSetup]=useState<boolean|null>(null),[offline,setOffline]=useState(!navigator.onLine)
  const [path,setPath]=useState(location.pathname),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [list,setList]=useState<Battery[]>([]),[detail,setDetail]=useState<Battery|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('')
  const [chargers,setChargers]=useState<Charger[]>([]),[chargerFilter,setChargerFilter]=useState(''),[channelFilter,setChannelFilter]=useState(''),[duplicateNumber,setDuplicateNumber]=useState<string|null>(null)
  useEffect(()=>{if(user)api<Charger[]>('/chargers').then(setChargers).catch(()=>{})},[user,path])
  const measuredEntries=filterMeasurements(detail?.entries||[],chargerFilter,channelFilter)
  const [showBattery,setShowBattery]=useState(false),[editBattery,setEditBattery]=useState(false),[entry,setEntry]=useState<Entry|null|false>(false),[entryKind,setEntryKind]=useState('charge'),[scan,setScan]=useState(false),[menu,setMenu]=useState(false),[guideOpen,setGuideOpen]=useState(false),[reauth,setReauth]=useState(false),[reauthError,setReauthError]=useState('')
  function go(to:string){history.pushState({},'',to);setPath(new URL(to,location.origin).pathname);setDetail(null);setError('');setShowBattery(false);setEntry(false);setMenu(false);setGuideOpen(false);setTransferOpen(false);setAnnotation(null);setDuplicateNumber(null);setChargerFilter('');setChannelFilter('')}
  useEffect(()=>{const pop=()=>{setPath(location.pathname);setEntry(false);setShowBattery(false)};window.addEventListener('popstate',pop);const online=()=>setOffline(!navigator.onLine);window.addEventListener('online',online);window.addEventListener('offline',online);api<User>('/auth/me').then(u=>{setUser(u);setSetup(false)}).catch(()=>api<{needed:boolean}>('/auth/setup').then(r=>setSetup(r.needed)));return()=>{window.removeEventListener('popstate',pop);window.removeEventListener('online',online);window.removeEventListener('offline',online)}},[])
  useEffect(()=>{if(!user)return;const failed=(e:unknown)=>{if(e instanceof ApiError&&e.status===401)setReauth(true);else setError((e as Error).message)};if(path.startsWith('/b/')){api<Battery>('/batteries/'+path.split('/')[2]).then(setDetail).catch(failed)}else{api<Battery[]>('/batteries?q='+encodeURIComponent(query)+'&status='+encodeURIComponent(filter)).then(setList).catch(failed)}},[user,path,query,filter])
  async function refresh(){if(path.startsWith('/b/'))setDetail(await api<Battery>('/batteries/'+path.split('/')[2]));else setList(await api<Battery[]>('/batteries?q='+encodeURIComponent(query)+'&status='+encodeURIComponent(filter)))}
  async function run(work:()=>Promise<void>){setError('');setBusy(true);try{await work()}catch(e){if(user&&e instanceof ApiError&&e.status===401){setReauthError('La session a expiré. Reconnectez-vous pour reprendre votre saisie.');setReauth(true)}else setError((e as Error).message)}finally{setBusy(false)}}
  if(setup===null&&!user)return <div className="loading">{offline?'Hors connexion — reconnectez-vous pour accéder à vos données.':'Chargement de LipoWatcher…'}</div>
  if((path==='/verify'&&user)||path==='/reset')return <TokenPage kind={path.slice(1)} token={linkToken} offline={offline} busy={busy} run={run} reconnect={()=>setUser(null)} done={()=>{if(user)api<User>('/auth/me').then(u=>{setUser(u);setSetup(false)}).catch(()=>setUser(null));go('/')}}/>
  if(!user)return <PublicAuth run={run} setup={!!setup} offline={offline} error={error} busy={busy} submit={(username,password)=>run(async()=>{const u=await api<User>(setup?'/auth/setup':'/auth/login',json('POST',{username,password}));setUser(u);setSetup(false)})}/>
  const current=path.startsWith('/b/')
  return <><header className="top"><div className="top-inner"><a className="brand" href="/" onClick={e=>{e.preventDefault();go('/')}}><span className="brand-icon"><BatteryCharging size={22}/></span><span>Lipo<span className="brand-light">Watcher</span></span></a><div className="top-actions"><span className="user-name">{user.email||user.username}</span><button className="iconbtn" aria-label="Menu" onClick={()=>setMenu(!menu)}><Menu size={22}/></button></div></div></header>
  {menu&&<div className="menu">{[['/','Mes batteries'],['/models','Modèles'],['/lots','Lots'],['/chargers','Mes chargeurs'],['/catalogue','Catalogue'],['/account','Mon compte'],['/transfers','Transferts']].map(([to,label])=><button key={to} onClick={()=>go(to)}>{label}</button>)}<button onClick={()=>{go('/labels')}}><Printer size={17}/> Planche d’étiquettes</button><a href="/api/export/batteries.csv"><Download size={17}/> Export batteries CSV</a><a href="/api/export/entries.csv"><Download size={17}/> Export sessions CSV</a>{user.is_admin===1&&<button onClick={()=>go('/users')}><Settings size={17}/> Ajouter un utilisateur</button>}<button onClick={()=>run(async()=>{await api('/auth/logout',{method:'POST'});setUser(null);setList([]);setDetail(null);setGuideOpen(false);setSetup(false);go('/')})}><LogOut size={17}/> Déconnexion</button></div>}
  {offline&&<div className="offline">Hors connexion — les saisies sont désactivées. Reconnectez-vous pour enregistrer.</div>}
  <nav className="workshop-nav" aria-label="Atelier">{[['/','Batteries'],['/models','Modèles'],['/lots','Lots'],['/chargers','Mes chargeurs'],['/catalogue','Catalogue'],['/account','Mon compte'],['/transfers','Transferts']].map(([to,label])=><button key={to} className={path===to?'selected':''} onClick={()=>go(to)}>{label}</button>)}</nav><main className="container">{error&&<div className="alert" role="alert">{error}<button onClick={()=>setError('')} aria-label="Fermer"><X size={16}/></button></div>}
  {path==='/account'?<Account key={user.id} user={user} updated={setUser} offline={offline} busy={busy} run={run}/>:path==='/transfers'||path==='/transfer'?<Transfers key={user.id+path} token={path==='/transfer'?linkToken:''} offline={offline} busy={busy} run={run} go={go}/>:['/models','/lots','/chargers','/catalogue'].includes(path)?<Inventory key={user.id+':'+path} view={path.slice(1)} user={user} offline={offline} busy={busy} run={run} go={go}/>:path==='/labels'?<Labels list={list} go={go}/>:path==='/users'?<Users offline={offline} run={run} busy={busy}/>:current?<>
    <button className="back" onClick={()=>go('/')}><ChevronLeft size={18}/> Toutes les batteries</button>
    {detail?<><button className="btn secondary" disabled={offline||busy} onClick={()=>setTransferOpen(true)}>Transférer cette batterie</button><div className="detail-head"><div><div className="eyebrow">FICHE BATTERIE</div><h1>#{detail.number}</h1><p>{detail.brand||'Batterie'} {detail.model} · {detail.chemistry} {detail.cells}S · {formatted(detail.nominal_mah)} mAh nominaux</p></div><span className={'badge '+detail.status}>{statusText[detail.status]}</span></div>
      <div className="hero-actions"><Button onClick={()=>{setEntryKind('charge');setEntry(null)}} disabled={offline}><CirclePlus size={18}/> Ajouter une charge</Button><Button variant="secondary" onClick={()=>{setEditBattery(true);setShowBattery(true)}} disabled={offline}>Modifier la fiche</Button><Button variant="secondary" disabled={offline} onClick={()=>setDuplicateNumber('')}>Dupliquer les caractéristiques</Button><Button variant="ghost" onClick={()=>go('/labels?one='+detail.id)}><QrCode size={17}/> Étiquette</Button></div>
      {(detail.model_id||detail.lot_id)&&<div className="notice">{detail.model_id&&<p>Instantané du modèle d’origine · révision {detail.model_revision}. Les éditions du modèle ne modifient pas cette fiche.</p>}{detail.lot_id&&<button className="btn secondary" onClick={()=>go('/lots?open='+detail.lot_id)}>Voir le lot d’achat</button>}</div>}
      {detail.condition==='new'&&<div className="notice guide-invite"><span>Première utilisation : une liste de vérifications facultative est disponible pour cette batterie.</span><Button variant="secondary" onClick={()=>setGuideOpen(true)}>Ouvrir le guide</Button></div>}
      <div className="stats"><Metric label="Charges enregistrées" value={formatted(detail.charge_count)} sub={detail.prior_cycles!=null?`+ ${detail.prior_cycles} cycles antérieurs déclarés`:'Historique antérieur non inclus'}/><Metric label="mAh ajoutés" value={formatted(detail.total_added_mah)} sub="Depuis l’ajout dans l’application"/><Metric label="Capacité nominale" value={`${formatted(detail.nominal_mah)} mAh`} sub="Déclarée sur l’étiquette"/></div>
      {detail.condition==='used'&&<div className="notice">Batterie d’occasion. {detail.prior_history==='unknown'?'Son historique antérieur est inconnu.':`Historique antérieur déclaré : ${detail.prior_cycles??'non chiffré'} cycles.`} Les compteurs ci-dessus concernent uniquement les sessions enregistrées ici.</div>}
      <section className="panel"><h2>Comparer les mesures</h2><div className="form-grid"><label>Chargeur<select value={chargerFilter} onChange={e=>{setChargerFilter(e.target.value);setChannelFilter('')}}><option value="">Tous les appareils</option>{chargers.map(c=><option key={c.id} value={'id:'+c.id}>{c.name}{c.status==='archived'?' (archivé)':''}</option>)}{Array.from(new Set((detail.entries||[]).filter(e=>!e.charger_id&&e.charger).map(e=>e.charger))).map(name=><option key={name} value={'text:'+name}>{name} (ancien texte)</option>)}</select></label><label>Canal<select value={channelFilter} onChange={e=>setChannelFilter(e.target.value)}><option value="">Tous les canaux</option><option value="none">Non renseigné</option>{Array.from(new Set((detail.entries||[]).filter(e=>e.charger_channel!=null).map(e=>e.charger_channel!))).sort((a,b)=>a-b).map(n=><option key={n} value={n}>Canal {n}</option>)}</select></label></div><small>{measuredEntries.length} session(s) retenue(s). Aucune correction automatique entre appareils. Comparez température, état de charge et conditions.</small></section>
      <div className="two-col"><section className="panel"><h2>Évolution des mesures</h2><Trends entries={measuredEntries}/></section><section className="panel"><h2>Repères de suivi</h2><Health entries={measuredEntries} nominal={detail.nominal_mah}/></section></div>
      <CellTrends entries={measuredEntries} cells={detail.cells}/>
      <section className="panel history"><div className="section-heading"><div><div className="eyebrow">JOURNAL</div><h2>Historique des sessions</h2></div><span className="count">{detail.entries?.length||0} saisie(s)</span></div>{detail.entries?.length?detail.entries.map(e=><EntryCard key={e.id} entry={e} onAnnotate={()=>{setAnnotation(e);setAnnotationText('')}} onEdit={()=>setEntry(e)} onDelete={()=>{if(confirm('Supprimer cette session ?'))run(async()=>{await api(`/batteries/${detail.id}/entries/${e.id}`,{method:'DELETE'});await refresh()})}} offline={offline}/>):<div className="empty"><BatteryFull size={32}/><h3>Aucune session enregistrée</h3><p>Ajoutez une charge pour commencer le suivi de cette batterie.</p><Button onClick={()=>setEntry(null)} disabled={offline}>Ajouter une charge</Button></div>}</section>
      {!!detail.transfer_chain?.length&&<section className="panel"><h2>Provenance des transferts</h2>{detail.transfer_chain.map((t,i)=><p key={i}>{new Date(t.closed_at).toLocaleString('fr-FR')} · {t.from_ref.slice(0,10)} → {t.to_ref.slice(0,10)}</p>)}<p>Historique déclaratif, sans certification de sécurité.</p></section>}<div className="danger-row">{!!detail.transfer_chain?.length?<p>Historique transféré conservé. Pour retirer cette batterie de l’usage, modifiez son statut.</p>:<button onClick={()=>{if(confirm(`Supprimer la batterie #${detail.number} et tout son historique ?`))run(async()=>{await api(`/batteries/${detail.id}`,{method:'DELETE'});go('/')})}} disabled={offline}>Supprimer cette batterie</button>}</div>
    </>:<div className="loading">Chargement de la fiche…</div>}</>:<><div className="page-heading"><div><div className="eyebrow">MON ATELIER</div><h1>Mes batteries</h1><p>Un carnet clair pour chaque charge, test et vol.</p></div><div className="heading-actions"><Button variant="secondary" onClick={()=>setScan(true)}><QrCode size={18}/> Scanner</Button><Button onClick={()=>{setEditBattery(false);setShowBattery(true)}} disabled={offline}><CirclePlus size={18}/> Ajouter</Button></div></div>
    <div className="toolbar"><label className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un numéro…" inputMode="search"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filtrer par statut"><option value="">Tous les statuts</option>{Object.entries(statusText).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
    <div className="list-meta">{list.length} batterie{list.length>1?'s':''}</div>{list.length?<div className="battery-grid">{list.map(b=><button className="battery-card" key={b.id} onClick={()=>{setDetail(null);go('/b/'+b.id)}}><div className="card-top"><div className="battery-number">#{b.number}</div><span className={'badge '+b.status}>{statusText[b.status]}</span></div><div className="battery-name">{b.brand||'Batterie'} {b.model}</div><div className="battery-spec">{b.chemistry} · {b.cells}S · {formatted(b.nominal_mah)} mAh</div><div className="card-bottom"><span><BatteryCharging size={16}/> {b.charge_count||0} charge(s)</span><span>Voir la fiche →</span></div></button>)}</div>:<div className="empty large"><BatteryFull size={38}/><h3>{query||filter?'Aucun résultat':'Votre suivi commence ici'}</h3><p>{query||filter?'Essayez un autre numéro ou statut.':'Ajoutez votre première batterie. Son numéro reste exactement tel que vous l’écrivez, zéros compris.'}</p>{!query&&!filter&&<Button onClick={()=>setShowBattery(true)} disabled={offline}>Ajouter une batterie</Button>}</div>}</>}
  </main>
  {transferOpen&&detail&&<TransferProposal key={user.id+detail.id} battery={detail} user={user} error={error} offline={offline} busy={busy} run={run} close={()=>setTransferOpen(false)} completed={()=>{setTransferOpen(false);go('/transfers')}}/>}
  {annotation&&detail&&<Modal title="Ajouter une annotation datée" close={()=>setAnnotation(null)}>{error&&<p className="alert" role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/batteries/${detail.id}/entries/${annotation.id}/annotations`,json('POST',{text:annotationText}));setAnnotation(null);await refresh()})}}><p>Le relevé original reste inchangé. L’annotation garde sa date et votre provenance pseudonyme. Texte privé par défaut ; son partage pourra être sélectionné dans un transfert.</p><label>Correction ou précision<textarea required maxLength={5000} value={annotationText} onChange={e=>setAnnotationText(e.target.value)}/></label><button className="btn primary" disabled={offline||busy||!annotationText.trim()}>Enregistrer l’annotation</button></form></Modal>}
  {showBattery&&<BatteryModal key={user.id+':'+(editBattery?detail?.id:'new')} userId={user.id} initial={editBattery?detail:null} offline={offline} busy={busy} error={error} close={()=>setShowBattery(false)} save={data=>run(async()=>{const payload=data as Record<string,unknown>;const numbers=String(payload.number).split(/[;,\n]+/).map(s=>s.trim()).filter(Boolean);if(!editBattery&&numbers.length>1){await api('/batteries/batch',json('POST',{numbers,template:{...payload,number:numbers[0]}}));clearDraft(sessionStorage,user.id,'new-battery','form');setShowBattery(false);go('/');await refresh()}else{const saved=await api<Battery>(editBattery?`/batteries/${detail!.id}`:'/batteries',json(editBattery?'PUT':'POST',{...payload,number:numbers[0]||''}));clearDraft(sessionStorage,user.id,editBattery?detail!.id:'new-battery','form');setShowBattery(false);if(editBattery)await refresh();else{setDetail(null);go('/b/'+saved.id);if(saved.condition==='new')setGuideOpen(true)}}})}/>}
  {entry!==false&&detail&&<EntryModal key={user.id+':'+detail.id+':'+(entry?.id||'new-'+entryKind)} userId={user.id} batteryId={detail.id} defaultKind={entryKind} initial={entry} cells={detail.cells} chargers={chargers} lastChoice={lastDeviceChoice(detail.entries||[],chargers)} offline={offline} busy={busy} error={error} close={()=>setEntry(false)} save={data=>run(async()=>{await api(`/batteries/${detail.id}/entries${entry?'/'+entry.id:''}`,json(entry?'PUT':'POST',data));clearDraft(sessionStorage,user.id,detail.id,entry?.id||'new-'+entryKind);setEntry(false);await refresh()})}/>}
  {duplicateNumber!==null&&detail&&<Modal title="Dupliquer les caractéristiques" close={()=>setDuplicateNumber(null)}><form onSubmit={e=>{e.preventDefault();run(async()=>{const b=await api<Battery>('/batteries/'+detail.id+'/duplicate',json('POST',{number:duplicateNumber}));setDuplicateNumber(null);setDetail(null);go('/b/'+b.id)})}}>{error&&<p className="alert" role="alert">{error}</p>}<p>La nouvelle batterie aura son propre numéro. Ses sessions, compteurs antérieurs et étapes cochées seront vides.</p><label>Nouveau numéro<input required value={duplicateNumber} onChange={e=>setDuplicateNumber(e.target.value)} placeholder="002"/></label><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setDuplicateNumber(null)}>Annuler</button><button className="btn primary" disabled={offline||busy}>Dupliquer</button></div></form></Modal>}
  {guideOpen&&detail&&detail.condition==='new'&&<FirstUseGuide battery={detail} offline={offline} busy={busy} onClose={()=>setGuideOpen(false)} onToggle={(key,done)=>run(async()=>{await api('/batteries/'+detail.id+'/guide/'+key,json('PUT',{done}));await refresh()})} onReference={()=>{setGuideOpen(false);setEntryKind('baseline');setEntry(null)}}/>}
  {reauth&&<Reauth username={user.username} error={reauthError} offline={offline} busy={busy} submit={(username,password)=>{setReauthError('');setBusy(true);api<User>('/auth/login',json('POST',{username,password})).then(async next=>{if(next.id!==user.id){setEntry(false);setShowBattery(false);setGuideOpen(false);setDetail(null);setList([]);setChargers([]);setDuplicateNumber(null);setUser(next);go('/')}else{setUser({...next});await refresh()}setReauth(false)}).catch(e=>setReauthError((e as Error).message)).finally(()=>setBusy(false))}}/>}
  {scan&&<Scanner close={()=>setScan(false)} found={id=>{setScan(false);setDetail(null);go('/b/'+id)}}/>}
  </>
}
function Reauth({username:initial,error,offline,busy,submit}:{username:string;error:string;offline:boolean;busy:boolean;submit:(u:string,p:string)=>void}){const [username,setUsername]=useState(initial),[password,setPassword]=useState('');return <div className="reauth-backdrop"><form className="auth-form reauth-form" role="dialog" aria-modal="true" aria-label="Session expirée" onSubmit={e=>{e.preventDefault();submit(username,password)}}><div className="eyebrow">SESSION EXPIRÉE</div><h2>Reconnectez-vous</h2><p>Votre formulaire reste dans ce navigateur. Il reprendra si vous utilisez le même compte. Avec un autre compte, ses brouillons restent séparés.</p>{error&&<div className="alert" role="alert">{error}</div>}<label>Identifiant<input required minLength={3} value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>Mot de passe<input required type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" autoFocus/></label><Button type="submit" disabled={offline||busy}>Reprendre</Button></form></div>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="metric"><div className="metric-label">{label}</div><strong>{value}</strong><small>{sub}</small></div>}
function EntryCard({entry:e,onEdit,onDelete,onAnnotate,offline}:{entry:Entry;onEdit:()=>void;onDelete:()=>void;onAnnotate:()=>void;offline:boolean}){const m=e.metrics;return <article className="entry-card"><div className="entry-top"><div><span className={'kind '+e.kind}>{kindText[e.kind]}</span><strong>{new Date(e.occurred_at).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</strong><small>{new Date(e.occurred_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></div><div className="entry-actions"><button onClick={onAnnotate} disabled={offline}>Annoter</button>{!e.locked&&<><button onClick={onEdit} disabled={offline}>Modifier</button><button onClick={onDelete} disabled={offline}>Supprimer</button></>}</div></div><div className="entry-main">{e.added_mah!=null&&<strong>+ {formatted(e.added_mah)} mAh</strong>}{e.discharged_mah!=null&&<strong>{formatted(e.discharged_mah)} mAh déchargés</strong>}{e.duration_min!=null&&<strong>{e.duration_min} min</strong>}{e.charger&&<span>{e.charger}{e.charger_channel!=null?' · canal '+e.charger_channel:''}</span>}</div>{Object.keys(m).length>0&&<div className="entry-measures">{m.measured_ratio!=null&&<span>Capacité mesurée : {m.measured_ratio}% du nominal</span>}{m.estimated_mah!=null&&<span>Estimation charge partielle : {formatted(Number(m.estimated_mah))} mAh</span>}{m.before_delta_v!=null&&<span>Écart avant : {m.before_delta_v} V</span>}{m.after_delta_v!=null&&<span>Écart après : {m.after_delta_v} V</span>}{m.resistance_delta_mohm!=null&&<span>Écart RI : {m.resistance_delta_mohm} mΩ</span>}{m.estimate_caution&&<small>{m.estimate_caution}</small>}{m.above_nominal_caution&&<small>{m.above_nominal_caution}</small>}</div>}{(e.notes||e.aircraft||e.voltage_sag||e.heat)&&<p className="entry-notes">{[e.aircraft,e.voltage_sag,e.heat,e.notes].filter(Boolean).join(' · ')}</p>}{e.origin_ref&&<small>Provenance {e.origin_ref.slice(0,10)}{e.locked?' · Relevé transféré verrouillé':''}</small>}{e.annotations?.map(a=><p className="entry-notes" key={a.id}>{new Date(a.created_at).toLocaleString('fr-FR')} · {a.origin_ref.slice(0,10)} : {a.text||'Texte non partagé'}</p>)}</article>}
function Health({entries,nominal}:{entries:Entry[];nominal:number}){const tests=entries.filter(e=>e.kind==='test'&&e.metrics.measured_mah!=null);const latest=tests[0];const estimates=entries.filter(e=>e.metrics.estimated_mah!=null);const resist=entries.find(e=>e.resistance_mohm);return <div className="health"><div className="health-row"><span>Capacité nominale déclarée</span><strong>{formatted(nominal)} mAh</strong></div><div className="health-row"><span>Dernier test de décharge</span><strong>{latest?`${formatted(Number(latest.metrics.measured_mah))} mAh · ${latest.metrics.measured_ratio}%`:'Aucun test'}</strong></div>{latest?.metrics.above_nominal_caution&&<div className="health-caution">{latest.metrics.above_nominal_caution}</div>}{latest&&<small>Mesuré le {new Date(latest.occurred_at).toLocaleDateString('fr-FR')}{latest.cutoff_v?` · coupure ${latest.cutoff_v} V`:''}{latest.current_a?` · ${latest.current_a} A`:''}{latest.ambient_c!=null?` · ${latest.ambient_c} °C`:''}</small>}<div className="health-row"><span>Estimation depuis une charge</span><strong>{estimates[0]?`${formatted(Number(estimates[0].metrics.estimated_mah))} mAh`:'Données insuffisantes'}</strong></div>{estimates[0]?.metrics.above_nominal_caution&&<div className="health-caution">{estimates[0].metrics.above_nominal_caution}</div>}{estimates[0]&&<small>Approximation, sensible au pourcentage initial et aux petites variations de charge.</small>}<div className="health-row"><span>Dernières résistances par cellule</span><strong>{resist?.resistance_mohm?.map(v=>v==null?'—':v+' mΩ').join(' · ')||'Aucune mesure'}</strong></div>{resist&&<small>Écart : {resist.metrics.resistance_delta_mohm??'—'} mΩ. Comparez les mesures dans des conditions similaires.</small>}<div className="health-warning">Ces indicateurs ne constituent pas un verdict de sécurité pour le vol. La résistance interne absolue, sans référence comparable, ne suffit pas à qualifier une batterie.</div></div>}
function Trends({entries}:{entries:Entry[]}){const series=[{key:'discharged_mah',label:'Capacité testée',unit:'mAh',color:'#d27848'},{key:'resistance_mean_mohm',label:'RI moyenne',unit:'mΩ',color:'#317d75'},{key:'after_delta_v',label:'Écart après équilibrage',unit:'V',color:'#6175ae'}];const [selected,setSelected]=useState(0);const s=series[selected];const points=entries.slice().reverse().map(e=>({date:e.occurred_at,value:s.key==='discharged_mah'?e.discharged_mah:Number(e.metrics[s.key])})).filter(p=>p.value!=null&&!Number.isNaN(p.value)) as {date:string,value:number}[];const min=Math.min(...points.map(p=>p.value)),max=Math.max(...points.map(p=>p.value));const y=(v:number)=>140-(max===min?0:(v-min)/(max-min)*115);return <><div className="chart-tabs">{series.map((item,i)=><button className={i===selected?'selected':''} onClick={()=>setSelected(i)} key={item.key}>{item.label}</button>)}</div>{points.length?<div className="chart-wrap"><svg viewBox="0 0 520 170" role="img" aria-label={`Graphique ${s.label}`} preserveAspectRatio="none"><line x1="20" y1="145" x2="500" y2="145" stroke="#dce3df"/><polyline points={points.map((p,i)=>`${20+(points.length===1?240:i*480/(points.length-1))},${y(p.value)}`).join(' ')} fill="none" stroke={s.color} strokeWidth="3"/>{points.map((p,i)=><circle key={i} cx={20+(points.length===1?240:i*480/(points.length-1))} cy={y(p.value)} r="5" fill={s.color}><title>{new Date(p.date).toLocaleDateString('fr-FR')} : {p.value} {s.unit}</title></circle>)}</svg><div className="chart-caption"><span>{new Date(points[0].date).toLocaleDateString('fr-FR')}</span><span>{points.length} mesure(s) · {s.unit}</span><span>{new Date(points[points.length-1].date).toLocaleDateString('fr-FR')}</span></div></div>:<div className="chart-empty"><ChartNoAxesCombined size={28}/><p>Aucune mesure de ce type pour l’instant.</p></div>}</>}
function Labels({list,go}:{list:Battery[];go:(s:string)=>void}){const one=new URLSearchParams(location.search).get('one');const [single,setSingle]=useState<Battery|null>(null);useEffect(()=>{if(one)api<Battery>('/batteries/'+one).then(setSingle).catch(()=>setSingle(null))},[one]);const selected=one?(single?[single]:[]):list;return <><button className="back no-print" onClick={()=>go(one?'/b/'+one:'/')}><ChevronLeft size={18}/> Retour</button><div className="page-heading no-print"><div><div className="eyebrow">IDENTIFICATION</div><h1>Étiquettes QR</h1><p>Scannez le code avec LipoWatcher pour ouvrir la fiche après connexion. Il ne contient aucun secret.</p></div><Button onClick={()=>window.print()}><Printer size={17}/> Imprimer</Button></div>{selected.length?<div className="labels-sheet">{selected.map(b=><div className="label" key={b.id}><img src={`/api/batteries/${b.id}/qr.png`} alt={`QR batterie ${b.number}`}/><div><strong>#{b.number}</strong><span>{b.chemistry} {b.cells}S · {b.nominal_mah} mAh</span><small>LipoWatcher</small></div></div>)}</div>:<div className="empty">Aucune batterie à imprimer.</div>}</>}
function Users({offline,run,busy}:{offline:boolean;run:(f:()=>Promise<void>)=>void;busy:boolean}){const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[done,setDone]=useState(false);return <><h1>Ajouter un utilisateur</h1><p>Chaque utilisateur ne voit que ses batteries et ses sessions.</p><form className="panel user-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api('/users',json('POST',{username,password}));setDone(true);setUsername('');setPassword('')})}}>{done&&<div className="notice">Compte créé.</div>}<label>Identifiant<input required minLength={3} value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Mot de passe initial<input required type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label><Button type="submit" disabled={busy||offline}>Créer le compte</Button></form></>}
function Scanner({close,found}:{close:()=>void;found:(id:string)=>void}){const video=React.useRef<HTMLVideoElement>(null);const canvas=React.useRef<HTMLCanvasElement>(null);const [message,setMessage]=useState('Autorisation caméra en attente…');useEffect(()=>{let stream:MediaStream|undefined,stop=false,frame=0;async function start(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(!video.current)return;video.current.srcObject=stream;await video.current.play();setMessage('Placez le code dans le cadre.');const Detector=(window as unknown as {BarcodeDetector?:new(o:{formats:string[]})=>{detect:(v:HTMLVideoElement)=>Promise<{rawValue:string}[]>}}).BarcodeDetector;const detector=Detector?new Detector({formats:['qr_code']}):null;const tick=async()=>{if(stop||!video.current)return;let value:string|undefined;try{if(detector)value=(await detector.detect(video.current))[0]?.rawValue;else if(canvas.current&&video.current.videoWidth){const c=canvas.current,ctx=c.getContext('2d')!;c.width=video.current.videoWidth;c.height=video.current.videoHeight;ctx.drawImage(video.current,0,0);const data=ctx.getImageData(0,0,c.width,c.height);value=jsQR(data.data,c.width,c.height)?.data}}catch{}if(value){const identifier=parseQrIdentifier(value);if(identifier){found(identifier);return}else setMessage('Ce QR ne correspond pas à une étiquette LipoWatcher.')}frame=requestAnimationFrame(tick)};tick()}catch{setMessage('Caméra indisponible. Utilisez la recherche par numéro.') }}start();return()=>{stop=true;cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop())}},[]);return <Modal title="Scanner une batterie" close={close}><div className="scanner"><video ref={video} playsInline muted/><canvas ref={canvas} hidden/><p>{message}</p></div></Modal>}
createRoot(document.getElementById('root')!).render(<App/>)
