import {useEffect,useState} from 'react'
import {api,json,ApiError,type Battery,type User} from './api'
import {Modal} from './Forms'

type Snapshot={battery:Record<string,unknown>;entries:Record<string,unknown>[];guide_steps:Record<string,unknown>[]}
type Transfer={id:string;battery_id:string;status:string;side:string;created_at:string;expires_at:string;closed_at:string|null;snapshot?:Snapshot;recipient_email?:string}
type Preview={snapshot:Snapshot;snapshot_hash:string;recipient_email:string;note_options:{key:string;text:string}[]}
type Props={offline:boolean;busy:boolean;run:(f:()=>Promise<void>)=>void;error?:string}
const labels:Record<string,string>={pending:'En attente',accepted:'Accepté',refused:'Refusé',canceled:'Annulé',expired:'Expiré',invalidated:'Invalidé : données modifiées'}
const fields:Record<string,string>={id:'Identifiant stable',brand:'Marque',model:'Référence',range:'Gamme',connector:'Connecteur',weight_g:'Masse (g)',chemistry:'Chimie',cells:'Cellules',nominal_mah:'Capacité nominale (mAh)',c_rating:'Décharge annoncée (C)',charge_c:'Charge documentée (C)',charge_max_a:'Maximum documenté (A)',charge_final_v:'Tension finale documentée du pack (V)',charge_rate_source:'Source des limites',manufacturer_guide_url:'Documentation fabricant',manufacturer_guide_scope:'Champ d’application',condition:'État à l’achat',prior_history:'Historique antérieur',prior_cycles:'Cycles antérieurs déclarés',status:'État déclaré',notes:'Notes sélectionnées',kind:'Type de session',occurred_at:'Moment du relevé',added_mah:'Charge ajoutée (mAh)',discharged_mah:'Décharge mesurée (mAh)',cutoff_v:'Tension de coupure (V)',initial_percent:'Charge initiale (%)',final_percent:'Charge finale (%)',before_v:'Tensions avant (V, par cellule)',after_v:'Tensions après (V, par cellule)',resistance_mohm:'Résistances (mΩ, par cellule)',current_a:'Courant (A)',ambient_c:'Température (°C)',duration_min:'Durée (min)',origin_ref:'Provenance pseudonyme',created_at:'Date d’enregistrement',initial_percent_source:'Conditions et source de l’estimation',voltage_sag:'Incident de tension sélectionné',heat:'Échauffement sélectionné',charger:'Chargeur technique et canal',annotations:'Annotations sélectionnées'}
const values:Record<string,string>={new:'Neuve',used:'Occasion',known:'Connu',unknown:'Inconnu',active:'Active',storage:'Stockage',check:'À contrôler',retired:'Retirée',charge:'Charge',test:'Décharge de test',flight:'Utilisation / vol',baseline:'Mesures de référence'}
function Attributes({data}:{data:Record<string,unknown>}){return <dl>{Object.entries(data).map(([key,value])=><div key={key}><dt>{fields[key]||key}</dt><dd>{value==null||value===''?'Non renseigné':Array.isArray(value)?value.map(v=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v)).join(' · '):typeof value==='object'?JSON.stringify(value):values[String(value)]||String(value)}</dd></div>)}</dl>}
function PreviewView({snapshot}:{snapshot:Snapshot}){return <div className="transfer-preview"><h3>Données transmises, intégralement</h3><p>Caractéristiques déclarées, relevés et étapes cochées. Aucune certification ni garantie de sécurité. Les identifiants de provenance sont pseudonymes. — indique une valeur absente.</p><details open><summary>Caractéristiques du pack</summary><Attributes data={snapshot.battery}/></details><details><summary>{snapshot.entries.length} session(s) : mesures, conditions, notes sélectionnées</summary>{snapshot.entries.map(e=><section key={String(e.id)}><h4>{new Date(String(e.occurred_at)).toLocaleString('fr-FR')}</h4><Attributes data={e}/></section>)}</details><details><summary>Étapes de première utilisation</summary><pre>{JSON.stringify(snapshot.guide_steps,null,2)}</pre></details></div>}
function noteLabel(key:string,snapshot:Snapshot){if(key==='battery.notes')return 'Fiche — notes';if(key.startsWith('annotation:'))return 'Annotation datée';const [,id,field]=key.split(':');const entry=snapshot.entries.find(e=>e.id===id);return `${entry?new Date(String(entry.occurred_at)).toLocaleString('fr-FR'):'Session'} — ${fields[field]||field}`}

export function TransferProposal({battery,user,close,completed,offline,busy,run,error}:{battery:Battery;user:User;close:()=>void;completed:()=>void}&Props){
 const [email,setEmail]=useState(''),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Preview|null>(null),[confirmed,setConfirmed]=useState(false)
 const valid=!!user.email_verified_at
 const build=(notes:string[])=>run(async()=>{setPreview(await api<Preview>(`/batteries/${battery.id}/transfer-preview`,json('POST',{recipient_email:email,share_notes:notes})));setSelected(notes);setConfirmed(false)})
 return <Modal title={'Transférer la batterie #'+battery.number} close={close}>{error&&<p className="alert" role="alert">{error}</p>}<p>Une batterie à la fois. Son UUID et ses QR restent identiques. Le destinataire doit vérifier exactement l’adresse invitée. L’envoi ne transfère rien.</p>{!valid?<p className="alert">Vérifiez votre adresse depuis Mon compte.</p>:<><form onSubmit={e=>{e.preventDefault();build(selected)}}><label>E-mail du destinataire<input required disabled={busy} type="email" value={email} onChange={e=>{setEmail(e.target.value);setPreview(null);setSelected([]);setConfirmed(false)}}/></label><button className="btn secondary" disabled={offline||busy}>Préparer l’aperçu</button></form>{preview&&<><p>Destinataire : <strong>{preview.recipient_email}</strong></p><p>Exclus : lot et prix d’achat, vendeur, date d’achat, références d’appareils privés, aéronef, compte, brouillons et noms personnels des chargeurs. Les champs libres sont privés par défaut.</p><fieldset><legend>Textes libres à partager explicitement</legend>{preview.note_options.length?preview.note_options.map(note=><label className="check" key={note.key}><input type="checkbox" disabled={offline||busy} checked={selected.includes(note.key)} onChange={e=>build(e.target.checked?[...selected,note.key]:selected.filter(key=>key!==note.key))}/><span>{noteLabel(note.key,preview.snapshot)}<br/>{note.text}</span></label>):<p>Aucun texte libre.</p>}</fieldset><PreviewView snapshot={preview.snapshot}/><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Je confirme cet aperçu et l’adresse destinataire. Toute modification des données invalidera la proposition.</span></label><button className="btn primary" disabled={offline||busy||!confirmed} onClick={()=>run(async()=>{await api(`/batteries/${battery.id}/transfers`,json('POST',{recipient_email:preview.recipient_email,share_notes:selected,snapshot_hash:preview.snapshot_hash}));completed()})}>Envoyer la proposition</button></>}</>}</Modal>
}

export function Transfers({token,offline,busy,run,go}:{token:string;go:(path:string)=>void}&Props){
 const [items,setItems]=useState<Transfer[]>([]),[detail,setDetail]=useState<Transfer|null>(null),[number,setNumber]=useState(''),[confirmed,setConfirmed]=useState(false),[localError,setError]=useState('')
 const load=async()=>setItems(await api<Transfer[]>('/transfers'))
 useEffect(()=>{const failure=(e:Error)=>{if(e instanceof ApiError&&e.status===401)run(async()=>{throw e});else setError(e.message)};load().catch(failure);if(token)api<Transfer>('/transfers/resolve',json('POST',{token})).then(setDetail).catch(failure)},[token])
 async function action(action:string){if(!detail)return;setDetail(await api<Transfer>(`/transfers/${detail.id}/${action}`,json('POST',{number,confirmed})));setConfirmed(false);await load()}
 return <><h1>Transferts de batteries</h1><p>Propositions envoyées et reçues. Les reçus clôturés donnent uniquement l’identifiant stable, les dates et le statut. Ils n’ouvrent pas l’historique futur.</p>{localError&&<p className="alert">{localError}</p>}<button className="btn secondary" disabled={offline||busy} onClick={()=>run(load)}>Actualiser</button><div className="transfer-list">{items.map(item=><button className="panel" key={item.id} onClick={()=>run(async()=>{setDetail(await api<Transfer>('/transfers/'+item.id));setNumber('');setConfirmed(false)})}><strong>{item.side==='sent'?'Envoyé':'Reçu'} — {labels[item.status]}</strong><small>{new Date(item.created_at).toLocaleString('fr-FR')}<br/>Batterie {item.battery_id}</small></button>)}</div>{!items.length&&<p>Aucune proposition accessible.</p>}{detail&&<section className="panel"><h2>{labels[detail.status]}</h2><p>Identifiant : {detail.battery_id}</p><p>Proposé le {new Date(detail.created_at).toLocaleString('fr-FR')} · expiration {new Date(detail.expires_at).toLocaleString('fr-FR')}{detail.closed_at?' · clôturé '+new Date(detail.closed_at).toLocaleString('fr-FR'):''}</p>{detail.recipient_email&&<p>Destinataire : {detail.recipient_email}</p>}{detail.snapshot&&<PreviewView snapshot={detail.snapshot}/>}<p>Historique déclaratif ; aucune décision de sécurité automatique.</p>{detail.status==='pending'?(detail.side==='sent'?<button className="btn secondary" disabled={offline||busy} onClick={()=>run(()=>action('cancel'))}>Annuler la proposition</button>:<><p>À l’acceptation, les relevés antérieurs restent verrouillés. Vous pourrez ajouter vos mesures et des annotations datées. Le propriétaire précédent perd l’accès à la fiche.</p><label>Numéro dans mon parc<input required maxLength={30} value={number} onChange={e=>setNumber(e.target.value)} placeholder="001"/></label><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>J’ai examiné les données et je confirme ce transfert vers mon compte.</span></label><div className="heading-actions"><button className="btn primary" disabled={offline||busy||!confirmed||!number.trim()} onClick={()=>run(()=>action('accept'))}>Accepter le transfert</button><button className="btn secondary" disabled={offline||busy} onClick={()=>run(()=>action('refuse'))}>Refuser</button></div></>):detail.status==='accepted'&&detail.side==='received'?<button className="btn primary" onClick={()=>go('/b/'+detail.battery_id)}>Ouvrir ma batterie</button>:null}</section>}</>
}
